training_module.welcome:
  path: '/custom-welcome-page'
  defaults:
    _controller: '\Drupal\training_module\Controller\TrainingController::welcome'
    _title: 'My first custom page in Drupal9'
  requirements:
    _permission: 'access content'


training_module.customform:
  path: '/custom-form-page'
  defaults:
    _controller: '\Drupal\training_module\Controller\FormController::customform'
    _title: 'My first form page in Drupal9'
  requirements:
    _permission: 'access content'


training_module.training_config:
  path: '/admin/config/training'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Training'
  requirements:
    _permission: 'access administration pages'

training_module.training_custom_settings:
  path: '/admin/config/training/custom'
  defaults:
    _form: '\Drupal\training_module\Form\CustomConfigForm'
    _title: 'Custom config form'
  requirements:
    _permission: 'administration site configuration'
