training_module.welcome:
  path: '/custom-welcome-page'
  defaults:
    _controller: '\Drupal\training_module\Controller\TrainingController::welcome'
    _title: 'My first custom page in Drupal9'
  requirements:
    _permission: 'access content'


training_module.customform:
  path: '/custom-form-page'
  defaults:
    _controller: '\Drupal\training_module\Controller\FormController::customform'
    _title: 'My first form page in Drupal9'
  requirements:
    _permission: 'access content'
