training_module.welcome:
  path: '/custom-welcome-page'
  defaults:
    _controller: '\Drupal\training_module\Controller\TrainingController::welcome'
    _title: 'My first custom page in Drupal9'
  requirements:
    _permission: 'access content'
